-- ==========================================================
-- Purpose : Business KPI calculations for executive reporting
-- ==========================================================

-- ==========================================================
-- KPI 1 : Total Revenue
--
-- Purpose:
-- Calculate the total revenue generated from all orders.

SELECT
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items;

-- ==========================================================
-- KPI 2 : Total Orders
--
-- Purpose:
-- Calculate the total number of orders.

SELECT
    COUNT(*) AS total_orders
FROM orders;

-- ==========================================================
-- KPI 3 : Average Order Value
--
-- Purpose:
-- Calculate the average value of an order.

SELECT
    ROUND(AVG(order_total), 2) AS average_order_value
FROM (
    SELECT
        order_id,
        SUM(price) AS order_total
    FROM order_items
    GROUP BY order_id
) t;

-- ==========================================================
-- KPI 4 : Total Customers
--
-- Purpose:
-- Count total customers.

SELECT
    COUNT(DISTINCT customer_unique_id) AS total_customers
FROM customers;

-- ==========================================================
-- KPI 5 : Total Sellers
--
-- Purpose:
-- Count total sellers.

SELECT
    COUNT(*) AS total_sellers
FROM sellers;

-- ==========================================================
-- KPI 6 : Total Products Sold
--
-- Purpose:
-- Calculate total products sold.

SELECT
    COUNT(*) AS total_products_sold
FROM order_items;

-- ==========================================================
-- KPI 7 : Revenue by Customer State
--

SELECT
    c.customer_state,
    ROUND(SUM(oi.price), 2) AS revenue
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_state
ORDER BY revenue DESC;

-- ==========================================================
-- KPI 8 : Monthly Revenue
--
-- Purpose:
-- Analyze monthly business growth.

SELECT
    TO_CHAR(o.order_purchase_timestamp, 'YYYY-MM') AS month,
    ROUND(SUM(oi.price), 2) AS monthly_revenue
FROM orders o
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY month
ORDER BY month;

-- ==========================================================
-- KPI 9 : Top Product Categories by Revenue


SELECT
    p.product_category_name,
    ROUND(SUM(oi.price), 2) AS revenue
FROM products p
INNER JOIN order_items oi
    ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;

-- ==========================================================
-- KPI 10 : Customer Lifetime Value
--
-- Purpose:
-- Calculate total revenue generated by each customer.

SELECT
    c.customer_unique_id,
    ROUND(SUM(oi.price), 2) AS customer_lifetime_value
FROM customers c
INNER JOIN orders o
    ON c.customer_id = o.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY c.customer_unique_id
ORDER BY customer_lifetime_value DESC
LIMIT 10;

-- ==========================================================
-- KPI 11 : Average Delivery Time

SELECT
AVG(order_delivered_customer_date - order_purchase_timestamp)
AS average_delivery_time
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- ==========================================================
-- KPI 12 : Payment Method Distribution

SELECT
    payment_type,
    COUNT(*) AS transactions,
    ROUND(SUM(payment_value), 2) AS revenue
FROM payments
GROUP BY payment_type
ORDER BY revenue DESC;

-- ==========================================================
