-- ==========================================================
-- Purpose : Advanced SQL analytics using Window Functions

-- ==========================================================


-- ==========================================================
-- Query 1 : Rank Sellers by Revenue
--
-- Purpose:
-- Rank sellers based on total revenue.


SELECT
    seller_id,
    ROUND(SUM(price),2) AS total_revenue,
    RANK() OVER (
        ORDER BY SUM(price) DESC
    ) AS seller_rank
FROM order_items
GROUP BY seller_id;

-- ==========================================================
-- Query 2 : Dense Rank Product Categories
--
-- Purpose:
-- Rank product categories by revenue.

SELECT
    p.product_category_name,
    ROUND(SUM(oi.price),2) AS revenue,
    DENSE_RANK() OVER (
        ORDER BY SUM(oi.price) DESC
    ) AS category_rank
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name;

-- ==========================================================
-- Query 3 : Product Category Ranking
--
-- Purpose:
-- Rank product categories based on the total revenue generated.

SELECT
    p.product_category_name,
    ROUND(SUM(oi.price),2) AS revenue,
    DENSE_RANK() OVER(
        ORDER BY SUM(oi.price) DESC
    ) AS category_rank
FROM products p
INNER JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name;

-- ==========================================================
-- Query 4 : Running Revenue
--
-- Purpose:
-- Calculate cumulative revenue over time.


SELECT
    order_purchase_timestamp::DATE AS order_date,
    SUM(oi.price) AS daily_revenue,
    SUM(SUM(oi.price))
    OVER(
        ORDER BY order_purchase_timestamp::DATE
    ) AS running_revenue
FROM orders o
INNER JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY order_purchase_timestamp::DATE
ORDER BY order_date;

-- ==========================================================
-- Query 5 : Monthly Revenue
--
-- Purpose:
-- Calculate revenue generated each month.

SELECT
    TO_CHAR(order_purchase_timestamp,'YYYY-MM' AS month,
    ROUND(SUM(price),2) AS revenue
FROM orders o
INNER JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY month
ORDER BY month;

-- ==========================================================
-- Query 6 : Average Order Value
--
-- Purpose:
-- Calculate the average value of each customer order.

SELECT
    ROUND(AVG(order_total),2) AS average_order_value
FROM(
    SELECT
    order_id,
    SUM(price) AS order_total
    FROM order_items
    GROUP BY order_id
)t;

-- ==========================================================
-- Query 7 : Top Product in Each Category
--
-- Purpose:
-- Find the highest revenue-generating product
-- within every product category.

WITH product_sales AS(
    SELECT
        p.product_category_name,
        oi.product_id,
        SUM(price) AS revenue
    FROM products p
    INNER JOIN order_items oi
    ON p.product_id=oi.product_id
    GROUP BY p.product_category_name,oi.product_id
)
SELECT *
FROM(
    SELECT *,
        ROW_NUMBER()
    OVER(
        PARTITION BY product_category_name
        ORDER BY revenue DESC
) AS row_num
FROM product_sales
)t
WHERE row_num=1;

-- ==========================================================
-- Query 8 : Sellers Above Average Revenue
--
-- Purpose:
-- Identify sellers whose revenue is greater than
-- the average seller revenue.

SELECT
    seller_id,
    SUM(price) AS revenue
FROM order_items
GROUP BY seller_id
HAVING SUM(price)>
(
    SELECT
        AVG(total_revenue)
    FROM(
    SELECT
        SUM(price) AS total_revenue
    FROM order_items
    GROUP BY seller_id
)t
);

-- ==========================================================
-- Query 9 : Average Delivery Time
--
-- Purpose:
-- Calculate the average number of days taken
-- to deliver an order.

SELECT
    AVG(
        DATE_PART(
            'day',
            order_delivered_customer_date - order_purchase_timestamp
        )
    )
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;

-- ==========================================================
-- Query 10 : Customer Lifetime Value
--
-- Purpose:
-- Calculate the total revenue generated by
-- each customer throughout their lifetime.

SELECT
    c.customer_unique_id,
ROUND(SUM(oi.price),2) AS customer_lifetime_value
FROM customers c
INNER JOIN orders o
ON c.customer_id=o.customer_id
INNER JOIN order_items oi
ON o.order_id=oi.order_id
GROUP BY c.customer_unique_id
ORDER BY customer_lifetime_value DESC;



